CC=g++
RM=rm -f

TARGET=expeb
SRCS=$(wildcard *.cpp)

CFLAGS=	-Wall -std=c++11 -g -O2

all: clean $(TARGET)32 $(TARGET)64

clean:
	$(RM) $(TARGET)32 $(TARGET)64
	rm -fR *.dSYM

$(TARGET)32: $(SRCS)
	$(CC) -o $@ $(CFLAGS) -m32 $(SRCS)

$(TARGET)64: $(SRCS)
	$(CC) -o $@ $(CFLAGS) $(SRCS)
